export const errorMap = {
  'auth/admin-restricted-operation': 'This operation is restricted to administrators only.',
  'auth/argument-error': 'An error occurred while processing the arguments.',
  'auth/app-not-authorized': 'This app is not authorized to use Firebase Authentication.',
  'auth/app-not-installed': 'The requested mobile application is not installed on this device.',
  'auth/captcha-check-failed': 'The reCAPTCHA check failed.',
  'auth/code-expired': 'The SMS code has expired.',
  'auth/cordova-not-ready': 'The Cordova framework is not ready.',
  'auth/cors-unsupported': 'This browser does not support CORS.',
  'auth/credential-already-in-use': 'This credential is already associated with a different user account.',
  'auth/custom-token-mismatch': 'The provided custom token does not match the expected format.',
  'auth/requires-recent-login': 'This operation requires recent authentication. Please log in again.',
  'auth/dependent-sdk-initialized-before-auth': 'The dependent SDK was initialized before Firebase Authentication.',
  'auth/dynamic-link-not-activated': 'Dynamic Links is not activated for this project.',
  'auth/email-change-needs-verification': 'Multi-factor users must always have a verified email.',
  'auth/email-already-in-use': 'The email address is already in use.',
  'auth/emulator-config-failed': 'Failed to configure the emulator.',
  'auth/expired-action-code': 'The action code has expired.',
  'auth/cancelled-popup-request': 'The popup request has been cancelled.',
  'auth/internal-error': 'An internal error has occurred.',
  'auth/invalid-api-key': 'The API key is invalid.',
  'auth/invalid-app-credential': 'The application credential is invalid.',
  'auth/invalid-app-id': 'The mobile app identifier is invalid.',
  'auth/invalid-user-token': 'The user token is invalid.',
  'auth/invalid-auth-event': 'An internal error has occurred.',
  'auth/invalid-cert-hash': 'The certificate hash is invalid.',
  'auth/invalid-verification-code': 'The verification code is invalid.',
  'auth/invalid-continue-uri': 'The continue URL is invalid.',
  'auth/invalid-cordova-configuration': 'The Cordova configuration is invalid.',
  'auth/invalid-custom-token': 'The custom token is invalid.',
  'auth/invalid-dynamic-link-domain': 'The dynamic link domain is invalid.',
  'auth/invalid-email': 'The email address is invalid.',
  'auth/invalid-emulator-scheme': 'The emulator scheme is invalid.',
  'auth/invalid-credential': 'The credential is invalid.',
  'auth/invalid-message-payload': 'The email message payload is invalid.',
  'auth/invalid-multi-factor-session': 'The multi-factor authentication session is invalid.',
  'auth/invalid-oauth-client-id': 'The OAuth client ID is invalid.',
  'auth/invalid-oauth-provider': 'The OAuth provider is invalid.',
  'auth/invalid-action-code': 'The action code is invalid.',
  'auth/unauthorized-domain': 'The domain is not authorized for OAuth operations.',
  'auth/wrong-password': 'The password is invalid.',
  'auth/invalid-persistence-type': 'The persistence type is invalid.',
  'auth/invalid-phone-number': 'The phone number is invalid.',
  'auth/invalid-provider-id': 'The provider ID is invalid.',
  'auth/invalid-recipient-email': 'The recipient email is invalid.',
  'auth/invalid-sender': 'The sender is invalid.',
  'auth/invalid-verification-id': 'The verification ID is invalid.',
  'auth/invalid-tenant-id': 'The tenant ID is invalid.',
  'auth/multi-factor-info-not-found': 'The multi-factor info was not found.',
  'auth/multi-factor-auth-required': 'Multi-factor authentication is required.',
  'auth/missing-android-pkg-name': 'The Android package name is missing.',
  'auth/missing-app-credential': 'The application credential is missing.',
  'auth/auth-domain-config-required': 'The Auth domain configuration is required.',
  'auth/missing-verification-code': 'The verification code is missing.',
  'auth/missing-continue-uri': 'The continue URL is missing.',
  'auth/missing-iframe-start': 'An internal error has occurred.',
  'auth/missing-ios-bundle-id': 'The iOS bundle ID is missing.',
  'auth/missing-or-invalid-nonce': 'The nonce is missing or invalid.',
  'auth/missing-multi-factor-info': 'The multi-factor info is missing.',
  'auth/missing-multi-factor-session': 'The multi-factor authentication session is missing.',
  'auth/missing-phone-number': 'The phone number is missing.',
  'auth/missing-verification-id': 'The verification ID is missing.',
  'auth/app-deleted': 'The FirebaseApp instance has been deleted.',
  'auth/account-exists-with-different-credential': 'An account already exists with the same email address but different sign-in credentials.',
  'auth/network-request-failed': 'A network request failed.',
  'auth/null-user': 'The user object is null.',
  'auth/no-auth-event': 'An internal error has occurred.',
  'auth/no-such-provider': 'The user is not linked to an account with the given provider.',
  'auth/operation-not-allowed': 'The operation is not allowed.',
  'auth/operation-not-supported-in-this-environment': 'This operation is not supported in the current environment.',
  'auth/popup-blocked': 'The popup was blocked by the browser.',
  'auth/popup-closed-by-user': 'The popup was closed by the user.',
  'auth/provider-already-linked': 'The user is already linked to an account with the given provider.',
  'auth/quota-exceeded': 'The quota for this operation has been exceeded.',
  'auth/redirect-cancelled-by-user': 'The redirect operation was cancelled by the user.',
  'auth/redirect-operation-pending': 'A redirect sign-in operation is already pending.',
  'auth/rejected-credential': 'The credential was rejected.',
  'auth/second-factor-already-in-use': 'The second factor is already in use.',
  'auth/maximum-second-factor-count-exceeded': 'The maximum number of second factors has been exceeded.',
  'auth/tenant-id-mismatch': 'The tenant ID does not match.',
  'auth/timeout': 'The operation timed out.',
  'auth/user-token-expired': 'The user token has expired.',
  'auth/too-many-requests': 'Too many requests. Please try again later.',
  'auth/unauthorized-continue-uri': 'The continue URL is not authorized.',
  'auth/unsupported-first-factor': 'Enrolling a second factor or signing in with a multi-factor account requires sign-in with a supported first factor.',
  'auth/unsupported-persistence-type': 'The persistence type is not supported in the current environment.',
  'auth/unsupported-tenant-operation': 'This operation is not supported in a multi-tenant context.',
  'auth/unverified-email': 'The operation requires a verified email address.',
  'auth/user-cancelled': 'The user cancelled the operation.',
  'auth/user-not-found': 'The user record does not exist.',
  'auth/user-disabled': 'The user account has been disabled.',
  'auth/user-mismatch': 'The supplied credentials do not correspond to the previously signed-in user.',
  'auth/user-signed-out': 'The user has signed out.',
  'auth/weak-password': 'The password is too weak.',
  'auth/web-storage-unsupported': 'Web storage is not supported in the current browser.',
  'auth/already-initialized': 'The FirebaseApp instance has already been initialized.',
  'auth/recaptcha-not-enabled': 'reCAPTCHA is not enabled for this project.',
  'auth/missing-recaptcha-token': 'The reCAPTCHA token is missing.',
  'auth/invalid-recaptcha-token': 'The reCAPTCHA token is invalid.',
  'auth/invalid-recaptcha-action': 'The reCAPTCHA action is invalid.',
  'auth/missing-client-type': 'The client type is missing.',
  'auth/missing-recaptcha-version': 'The reCAPTCHA version is missing.',
  'auth/invalid-recaptcha-version': 'The reCAPTCHA version is invalid.',
  'auth/invalid-req-type': 'The request type is invalid.',

  // Please note that these descriptions are based on the error codes provided and may not cover all possible scenarios.
}
