/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddProductToOrder: typeof import('./src/components/Product/AddProductToOrder.vue')['default']
    AskForPushNotifications: typeof import('./src/components/AskForPushNotifications.vue')['default']
    CancelOrder: typeof import('./src/components/CancelOrder.vue')['default']
    ChatMessage: typeof import('./src/components/ChatMessage.vue')['default']
    CloseIcon: typeof import('./src/components/CloseIcon.vue')['default']
    DetailCard: typeof import('./src/components/DetailCard.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    LoginComponent: typeof import('./src/components/LoginComponent.vue')['default']
    Map: typeof import('./src/components/Map.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    ModifyAddress: typeof import('./src/components/Address/ModifyAddress.vue')['default']
    OutlinedButton: typeof import('./src/components/OutlinedButton.vue')['default']
    PrimaryButton: typeof import('./src/components/PrimaryButton.vue')['default']
    RegisterComponent: typeof import('./src/components/RegisterComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectBox: typeof import('./src/components/SelectBox.vue')['default']
    Spinner: typeof import('./src/components/Spinner.vue')['default']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
  }
}
